services:
  # Source MySQL Database
  mysql-source:
    image: mysql:8.0
    container_name: mysql-source
    environment:
      MYSQL_ROOT_PASSWORD: sourcepass
      MYSQL_DATABASE: sakila
    ports:
      - "3306:3306"
    volumes:
      - mysql_source_data:/var/lib/mysql
      - ./sql/source:/docker-entrypoint-initdb.d
      - shared-data:/opt/airflow/shared
    networks:
      - etl_network

  # Data Warehouse MySQL
  mysql-warehouse:
    image: mysql:8.0
    container_name: mysql-warehouse
    environment:
      MYSQL_ROOT_PASSWORD: warehousepass
      MYSQL_DATABASE: sakila_dw
    ports:
      - "3307:3306"
    volumes:
      - mysql_warehouse_data:/var/lib/mysql
      - ./sql/warehouse:/docker-entrypoint-initdb.d
    networks:
      - etl_network

  # Airflow Database
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etl_network

  # Airflow Webserver
  airflow-webserver:
    build: .
    container_name: airflow-webserver
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=your-fernet-key-here
      - AIRFLOW__WEBSERVER__DEFAULT_USER_USERNAME=admin
      - AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD=admin
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./spark:/opt/spark
      - ./data:/opt/data
      - shared-data:/opt/airflow/shared
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - etl_network

  # Airflow Scheduler
  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=your-fernet-key-here
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./spark:/opt/spark
      - ./data:/opt/data
      - shared-data:/opt/airflow/shared
    command: scheduler
    networks:
      - etl_network

volumes:
  mysql_source_data:
  mysql_warehouse_data:
  postgres_data:
  shared-data:  
networks:
  etl_network:
    driver: bridge