
services:
  # Source MySQL Database
  mysql-source:
    image: mysql:8.0
    container_name: mysql-source
    environment:
      MYSQL_ROOT_PASSWORD: sourcepass
      MYSQL_DATABASE: sakila
    ports:
      - "3306:3306"
    volumes:
      - mysql_source_data:/var/lib/mysql
      - ./sql/source:/docker-entrypoint-initdb.d
    networks:
      - etl_network

  # Data Warehouse MySQL
  mysql-warehouse:
    image: mysql:8.0
    container_name: mysql-warehouse
    environment:
      MYSQL_ROOT_PASSWORD: warehousepass
      MYSQL_DATABASE: warehouse_db
      MYSQL_USER: warehouse_user
      MYSQL_PASSWORD: warehouse_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_warehouse_data:/var/lib/mysql
      - ./sql/warehouse:/docker-entrypoint-initdb.d
    networks:
      - etl_network

  # Airflow Database
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etl_network

  # Airflow Webserver
  airflow-webserver:
    build: .
    container_name: airflow-webserver
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=your-fernet-key-here
      - AIRFLOW__WEBSERVER__DEFAULT_USER_USERNAME=admin
      - AIRFLOW__WEBSERVER__DEFAULT_USER_PASSWORD=admin
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./spark:/opt/spark
      - ./data:/opt/data
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - etl_network

  # Airflow Scheduler
  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=your-fernet-key-here
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./spark:/opt/spark
      - ./data:/opt/data
    command: scheduler
    networks:
      - etl_network

  # Spark Master
  spark-master:
    image: bitnami/spark:3.5
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "7077:7077"
      - "8081:8080"
    volumes:
      - ./spark:/opt/spark-apps
      - ./data:/opt/data
    networks:
      - etl_network

  # Spark Worker
  spark-worker:
    image: bitnami/spark:3.5
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark:/opt/spark-apps
      - ./data:/opt/data
    networks:
      - etl_network

volumes:
  mysql_source_data:
  mysql_warehouse_data:
  postgres_data:

networks:
  etl_network:
    driver: bridge